// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup top module instance
    , TOP{this, namep}
{
    // Check resources
    Verilated::stackCheck(346);
    // Setup sub module instances
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscopep_PixelLogic = new VerilatedScope{this, "PixelLogic", "PixelLogic", "PixelLogic", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__PixelCTRL = new VerilatedScope{this, "PixelLogic.PixelCTRL", "PixelCTRL", "PixelCTRL", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__PixelCTRL__CG_tot_rst = new VerilatedScope{this, "PixelLogic.PixelCTRL.CG_tot_rst", "CG_tot_rst", "CG_MOD", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotCounter = new VerilatedScope{this, "PixelLogic.TotCounter", "TotCounter", "TotCounter", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotCounter__ff0 = new VerilatedScope{this, "PixelLogic.TotCounter.ff0", "ff0", "TFF_NCLK_NRST", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotCounter__ff1 = new VerilatedScope{this, "PixelLogic.TotCounter.ff1", "ff1", "TFF_NCLK_NRST", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotCounter__ff2 = new VerilatedScope{this, "PixelLogic.TotCounter.ff2", "ff2", "TFF_NCLK_NRST", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotCounter__ff3 = new VerilatedScope{this, "PixelLogic.TotCounter.ff3", "ff3", "TFF_NCLK_NRST", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotCounter__ff4 = new VerilatedScope{this, "PixelLogic.TotCounter.ff4", "ff4", "TFF_NCLK_NRST", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotCounter__ff5 = new VerilatedScope{this, "PixelLogic.TotCounter.ff5", "ff5", "SFF_NCLK_NRST", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotMemory = new VerilatedScope{this, "PixelLogic.TotMemory", "TotMemory", "TotMemory", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET__ = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[0]", "TotMem[0]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[0].MultiBitLatch", "MultiBitLatch", "LNQD1shrinkX4_V2", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET__ = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[1]", "TotMem[1]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[1].MultiBitLatch", "MultiBitLatch", "LNQD1shrinkX4_V2", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET__ = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[2]", "TotMem[2]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[2].MultiBitLatch", "MultiBitLatch", "LNQD1shrinkX4_V2", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET__ = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[3]", "TotMem[3]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[3].MultiBitLatch", "MultiBitLatch", "LNQD1shrinkX4_V2", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET__ = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[4]", "TotMem[4]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[4].MultiBitLatch", "MultiBitLatch", "LNQD1shrinkX4_V2", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET__ = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[5]", "TotMem[5]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[5].MultiBitLatch", "MultiBitLatch", "LNQD1shrinkX4_V2", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET__ = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[6]", "TotMem[6]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[6].MultiBitLatch", "MultiBitLatch", "LNQD1shrinkX4_V2", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET__ = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[7]", "TotMem[7]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch = new VerilatedScope{this, "PixelLogic.TotMemory.TotMem[7].MultiBitLatch", "MultiBitLatch", "LNQD1shrinkX4_V2", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_TOP = new VerilatedScope{this, "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER};
    // Set up scope hierarchy
    __Vhier.add(0, __Vscopep_PixelLogic);
    __Vhier.add(__Vscopep_PixelLogic, __Vscopep_PixelLogic__PixelCTRL);
    __Vhier.add(__Vscopep_PixelLogic, __Vscopep_PixelLogic__TotCounter);
    __Vhier.add(__Vscopep_PixelLogic, __Vscopep_PixelLogic__TotMemory);
    __Vhier.add(__Vscopep_PixelLogic__PixelCTRL, __Vscopep_PixelLogic__PixelCTRL__CG_tot_rst);
    __Vhier.add(__Vscopep_PixelLogic__TotCounter, __Vscopep_PixelLogic__TotCounter__ff0);
    __Vhier.add(__Vscopep_PixelLogic__TotCounter, __Vscopep_PixelLogic__TotCounter__ff1);
    __Vhier.add(__Vscopep_PixelLogic__TotCounter, __Vscopep_PixelLogic__TotCounter__ff2);
    __Vhier.add(__Vscopep_PixelLogic__TotCounter, __Vscopep_PixelLogic__TotCounter__ff3);
    __Vhier.add(__Vscopep_PixelLogic__TotCounter, __Vscopep_PixelLogic__TotCounter__ff4);
    __Vhier.add(__Vscopep_PixelLogic__TotCounter, __Vscopep_PixelLogic__TotCounter__ff5);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET__);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET__);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET__);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET__);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET__);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET__);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET__);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET__);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch);
    __Vhier.add(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch);
    // Setup export functions - final: 0
    // Setup export functions - final: 1
    // Setup public variables
    __Vscopep_PixelLogic->varInsert("CntRst", &(TOP.PixelLogic__DOT__CntRst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic->varInsert("Hit", &(TOP.PixelLogic__DOT__Hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic->varInsert("HitLe", &(TOP.PixelLogic__DOT__HitLe), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic->varInsert("HitLeAny", &(TOP.PixelLogic__DOT__HitLeAny), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic->varInsert("HitTe", &(TOP.PixelLogic__DOT__HitTe), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic->varInsert("PixelClkEn", &(TOP.PixelLogic__DOT__PixelClkEn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic->varInsert("PixelClkGated", &(TOP.PixelLogic__DOT__PixelClkGated), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic->varInsert("Reset_b", &(TOP.PixelLogic__DOT__Reset_b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic->varInsert("Tot6to4Mapping", &(TOP.PixelLogic__DOT__Tot6to4Mapping), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic->varInsert("TotDualEdgeCount", &(TOP.PixelLogic__DOT__TotDualEdgeCount), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic->varInsert("TotMemDataOut", &(TOP.PixelLogic__DOT__TotMemDataOut), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_PixelLogic->varInsert("TotMemReadAddr", &(TOP.PixelLogic__DOT__TotMemReadAddr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_PixelLogic->varInsert("TotMemWriteAddr", &(TOP.PixelLogic__DOT__TotMemWriteAddr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_PixelLogic->varInsert("tot_cnt", &(TOP.PixelLogic__DOT__tot_cnt), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_PixelLogic->varInsert("tot_overflow", &(TOP.PixelLogic__DOT__tot_overflow), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL->varInsert("CntRst", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__CntRst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL->varInsert("Hit", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__Hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL->varInsert("HitLe", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__HitLe), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL->varInsert("HitTe", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__HitTe), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL->varInsert("PixelClkEn", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__PixelClkEn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL->varInsert("PixelClkGated", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__PixelClkGated), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL->varInsert("Reset_b", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__Reset_b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL->varInsert("TotOverflow", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__TotOverflow), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL->varInsert("hit_rise", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__hit_rise), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL->varInsert("pix_rst", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__pix_rst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL->varInsert("pix_state_idle", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__pix_state_idle), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL->varInsert("rst_FF", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__rst_FF), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL->varInsert("state_sr", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__state_sr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_PixelLogic__PixelCTRL__CG_tot_rst->varInsert("ClkIn", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__CG_tot_rst__DOT__ClkIn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL__CG_tot_rst->varInsert("ClkOut", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__CG_tot_rst__DOT__ClkOut), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL__CG_tot_rst->varInsert("Enable", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__CG_tot_rst__DOT__Enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL__CG_tot_rst->varInsert("ck_inb", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__CG_tot_rst__DOT__ck_inb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__PixelCTRL__CG_tot_rst->varInsert("enl", &(TOP.PixelLogic__DOT__PixelCTRL__DOT__CG_tot_rst__DOT__enl), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter->varInsert("CntRst", &(TOP.PixelLogic__DOT__TotCounter__DOT__CntRst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter->varInsert("Hit", &(TOP.PixelLogic__DOT__TotCounter__DOT__Hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter->varInsert("HitTe", &(TOP.PixelLogic__DOT__TotCounter__DOT__HitTe), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter->varInsert("PixelClkGated", &(TOP.PixelLogic__DOT__TotCounter__DOT__PixelClkGated), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter->varInsert("Reset_b", &(TOP.PixelLogic__DOT__TotCounter__DOT__Reset_b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter->varInsert("Tot6to4Mapping", &(TOP.PixelLogic__DOT__TotCounter__DOT__Tot6to4Mapping), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter->varInsert("TotCnt", &(TOP.PixelLogic__DOT__TotCounter__DOT__TotCnt), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_PixelLogic__TotCounter->varInsert("TotDualEdgeCount", &(TOP.PixelLogic__DOT__TotCounter__DOT__TotDualEdgeCount), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter->varInsert("TotOverflow", &(TOP.PixelLogic__DOT__TotCounter__DOT__TotOverflow), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotCounter->varInsert("cnt_clk", &(TOP.PixelLogic__DOT__TotCounter__DOT__cnt_clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter->varInsert("cnt_rst_b", &(TOP.PixelLogic__DOT__TotCounter__DOT__cnt_rst_b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotCounter->varInsert("fall_phase", &(TOP.PixelLogic__DOT__TotCounter__DOT__fall_phase), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotCounter->varInsert("ff1_clk", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff1_clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotCounter->varInsert("init_tot_cnt", &(TOP.PixelLogic__DOT__TotCounter__DOT__init_tot_cnt), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,5,0);
    __Vscopep_PixelLogic__TotCounter->varInsert("rcnt_q", &(TOP.PixelLogic__DOT__TotCounter__DOT__rcnt_q), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,5,0);
    __Vscopep_PixelLogic__TotCounter->varInsert("rcnt_qn", &(TOP.PixelLogic__DOT__TotCounter__DOT__rcnt_qn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,5,0);
    __Vscopep_PixelLogic__TotCounter->varInsert("tot_cnt_int", &(TOP.PixelLogic__DOT__TotCounter__DOT__tot_cnt_int), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_PixelLogic__TotCounter->varInsert("tot_cnt_stageone", &(TOP.PixelLogic__DOT__TotCounter__DOT__tot_cnt_stageone), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,5,0);
    __Vscopep_PixelLogic__TotCounter__ff0->varInsert("nclk", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff0__DOT__nclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff0->varInsert("nrst", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff0__DOT__nrst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff0->varInsert("q", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff0__DOT__q), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff0->varInsert("qn", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff0__DOT__qn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff1->varInsert("nclk", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff1__DOT__nclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff1->varInsert("nrst", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff1__DOT__nrst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff1->varInsert("q", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff1__DOT__q), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff1->varInsert("qn", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff1__DOT__qn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff2->varInsert("nclk", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff2__DOT__nclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff2->varInsert("nrst", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff2__DOT__nrst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff2->varInsert("q", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff2__DOT__q), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff2->varInsert("qn", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff2__DOT__qn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff3->varInsert("nclk", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff3__DOT__nclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff3->varInsert("nrst", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff3__DOT__nrst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff3->varInsert("q", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff3__DOT__q), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff3->varInsert("qn", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff3__DOT__qn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff4->varInsert("nclk", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff4__DOT__nclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff4->varInsert("nrst", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff4__DOT__nrst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff4->varInsert("q", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff4__DOT__q), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff4->varInsert("qn", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff4__DOT__qn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff5->varInsert("nclk", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff5__DOT__nclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff5->varInsert("nrst", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff5__DOT__nrst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff5->varInsert("q", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff5__DOT__q), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotCounter__ff5->varInsert("qn", &(TOP.PixelLogic__DOT__TotCounter__DOT__ff5__DOT__qn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory->varInsert("HitLe", &(TOP.PixelLogic__DOT__TotMemory__DOT__HitLe), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory->varInsert("HitLeAny", &(TOP.PixelLogic__DOT__TotMemory__DOT__HitLeAny), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory->varInsert("HitTe", &(TOP.PixelLogic__DOT__TotMemory__DOT__HitTe), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory->varInsert("PixelClkGated", &(TOP.PixelLogic__DOT__TotMemory__DOT__PixelClkGated), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory->varInsert("TotMemDataIn", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMemDataIn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_PixelLogic__TotMemory->varInsert("TotMemDataOut", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMemDataOut), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_PixelLogic__TotMemory->varInsert("TotMemReadAddr", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMemReadAddr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_PixelLogic__TotMemory->varInsert("TotMemWriteAddr", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMemWriteAddr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_PixelLogic__TotMemory->varInsert("tot_mem", &(TOP.PixelLogic__DOT__TotMemory__DOT__tot_mem), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,7,0 ,3,0);
    __Vscopep_PixelLogic__TotMemory->varInsert("tot_mem_out", &(TOP.PixelLogic__DOT__TotMemory__DOT__tot_mem_out), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 1, 1 ,7,0 ,3,0);
    __Vscopep_PixelLogic__TotMemory->varInsert("tot_mem_write_addr_reg", &(TOP.PixelLogic__DOT__TotMemory__DOT__tot_mem_write_addr_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET__->varInsert("latch_condition", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__latch_condition), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET__->varInsert("latch_empty_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__latch_empty_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET__->varInsert("latch_en", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__latch_en), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET__->varInsert("latch_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__latch_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET__->varInsert("latch_input", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__latch_input), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch->varInsert("D0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__MultiBitLatch__DOT__D0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch->varInsert("D1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__MultiBitLatch__DOT__D1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch->varInsert("D2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__MultiBitLatch__DOT__D2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch->varInsert("D3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__MultiBitLatch__DOT__D3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch->varInsert("EN", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__MultiBitLatch__DOT__EN), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch->varInsert("Q0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__MultiBitLatch__DOT__Q0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch->varInsert("Q1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__MultiBitLatch__DOT__Q1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch->varInsert("Q2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__MultiBitLatch__DOT__Q2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch->varInsert("Q3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__0__KET____DOT__MultiBitLatch__DOT__Q3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET__->varInsert("latch_condition", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__latch_condition), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET__->varInsert("latch_empty_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__latch_empty_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET__->varInsert("latch_en", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__latch_en), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET__->varInsert("latch_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__latch_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET__->varInsert("latch_input", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__latch_input), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch->varInsert("D0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__MultiBitLatch__DOT__D0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch->varInsert("D1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__MultiBitLatch__DOT__D1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch->varInsert("D2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__MultiBitLatch__DOT__D2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch->varInsert("D3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__MultiBitLatch__DOT__D3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch->varInsert("EN", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__MultiBitLatch__DOT__EN), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch->varInsert("Q0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__MultiBitLatch__DOT__Q0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch->varInsert("Q1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__MultiBitLatch__DOT__Q1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch->varInsert("Q2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__MultiBitLatch__DOT__Q2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch->varInsert("Q3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__1__KET____DOT__MultiBitLatch__DOT__Q3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET__->varInsert("latch_condition", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__latch_condition), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET__->varInsert("latch_empty_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__latch_empty_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET__->varInsert("latch_en", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__latch_en), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET__->varInsert("latch_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__latch_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET__->varInsert("latch_input", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__latch_input), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch->varInsert("D0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__MultiBitLatch__DOT__D0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch->varInsert("D1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__MultiBitLatch__DOT__D1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch->varInsert("D2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__MultiBitLatch__DOT__D2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch->varInsert("D3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__MultiBitLatch__DOT__D3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch->varInsert("EN", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__MultiBitLatch__DOT__EN), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch->varInsert("Q0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__MultiBitLatch__DOT__Q0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch->varInsert("Q1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__MultiBitLatch__DOT__Q1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch->varInsert("Q2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__MultiBitLatch__DOT__Q2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch->varInsert("Q3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__2__KET____DOT__MultiBitLatch__DOT__Q3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET__->varInsert("latch_condition", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__latch_condition), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET__->varInsert("latch_empty_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__latch_empty_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET__->varInsert("latch_en", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__latch_en), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET__->varInsert("latch_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__latch_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET__->varInsert("latch_input", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__latch_input), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch->varInsert("D0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__MultiBitLatch__DOT__D0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch->varInsert("D1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__MultiBitLatch__DOT__D1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch->varInsert("D2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__MultiBitLatch__DOT__D2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch->varInsert("D3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__MultiBitLatch__DOT__D3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch->varInsert("EN", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__MultiBitLatch__DOT__EN), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch->varInsert("Q0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__MultiBitLatch__DOT__Q0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch->varInsert("Q1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__MultiBitLatch__DOT__Q1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch->varInsert("Q2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__MultiBitLatch__DOT__Q2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch->varInsert("Q3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__3__KET____DOT__MultiBitLatch__DOT__Q3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET__->varInsert("latch_condition", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__latch_condition), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET__->varInsert("latch_empty_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__latch_empty_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET__->varInsert("latch_en", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__latch_en), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET__->varInsert("latch_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__latch_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET__->varInsert("latch_input", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__latch_input), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch->varInsert("D0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__MultiBitLatch__DOT__D0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch->varInsert("D1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__MultiBitLatch__DOT__D1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch->varInsert("D2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__MultiBitLatch__DOT__D2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch->varInsert("D3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__MultiBitLatch__DOT__D3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch->varInsert("EN", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__MultiBitLatch__DOT__EN), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch->varInsert("Q0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__MultiBitLatch__DOT__Q0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch->varInsert("Q1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__MultiBitLatch__DOT__Q1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch->varInsert("Q2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__MultiBitLatch__DOT__Q2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch->varInsert("Q3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__4__KET____DOT__MultiBitLatch__DOT__Q3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET__->varInsert("latch_condition", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__latch_condition), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET__->varInsert("latch_empty_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__latch_empty_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET__->varInsert("latch_en", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__latch_en), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET__->varInsert("latch_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__latch_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET__->varInsert("latch_input", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__latch_input), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch->varInsert("D0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__MultiBitLatch__DOT__D0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch->varInsert("D1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__MultiBitLatch__DOT__D1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch->varInsert("D2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__MultiBitLatch__DOT__D2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch->varInsert("D3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__MultiBitLatch__DOT__D3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch->varInsert("EN", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__MultiBitLatch__DOT__EN), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch->varInsert("Q0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__MultiBitLatch__DOT__Q0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch->varInsert("Q1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__MultiBitLatch__DOT__Q1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch->varInsert("Q2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__MultiBitLatch__DOT__Q2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch->varInsert("Q3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__5__KET____DOT__MultiBitLatch__DOT__Q3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET__->varInsert("latch_condition", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__latch_condition), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET__->varInsert("latch_empty_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__latch_empty_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET__->varInsert("latch_en", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__latch_en), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET__->varInsert("latch_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__latch_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET__->varInsert("latch_input", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__latch_input), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch->varInsert("D0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__MultiBitLatch__DOT__D0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch->varInsert("D1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__MultiBitLatch__DOT__D1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch->varInsert("D2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__MultiBitLatch__DOT__D2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch->varInsert("D3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__MultiBitLatch__DOT__D3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch->varInsert("EN", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__MultiBitLatch__DOT__EN), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch->varInsert("Q0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__MultiBitLatch__DOT__Q0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch->varInsert("Q1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__MultiBitLatch__DOT__Q1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch->varInsert("Q2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__MultiBitLatch__DOT__Q2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch->varInsert("Q3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__6__KET____DOT__MultiBitLatch__DOT__Q3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET__->varInsert("latch_condition", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__latch_condition), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET__->varInsert("latch_empty_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__latch_empty_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET__->varInsert("latch_en", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__latch_en), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET__->varInsert("latch_hit", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__latch_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET__->varInsert("latch_input", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__latch_input), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch->varInsert("D0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__MultiBitLatch__DOT__D0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch->varInsert("D1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__MultiBitLatch__DOT__D1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch->varInsert("D2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__MultiBitLatch__DOT__D2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch->varInsert("D3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__MultiBitLatch__DOT__D3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch->varInsert("EN", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__MultiBitLatch__DOT__EN), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch->varInsert("Q0", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__MultiBitLatch__DOT__Q0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch->varInsert("Q1", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__MultiBitLatch__DOT__Q1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch->varInsert("Q2", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__MultiBitLatch__DOT__Q2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch->varInsert("Q3", &(TOP.PixelLogic__DOT__TotMemory__DOT__TotMem__BRA__7__KET____DOT__MultiBitLatch__DOT__Q3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("Hit", &(TOP.Hit), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("HitLe", &(TOP.HitLe), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("HitLeAny", &(TOP.HitLeAny), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("PixelClkEn", &(TOP.PixelClkEn), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("PixelClkGated", &(TOP.PixelClkGated), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("Reset_b", &(TOP.Reset_b), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("Tot6to4Mapping", &(TOP.Tot6to4Mapping), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("TotDualEdgeCount", &(TOP.TotDualEdgeCount), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("TotMemDataOut", &(TOP.TotMemDataOut), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_TOP->varInsert("TotMemReadAddr", &(TOP.TotMemReadAddr), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_TOP->varInsert("TotMemWriteAddr", &(TOP.TotMemWriteAddr), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 1 ,7,0);
}

Vtop__Syms::~Vtop__Syms() {
    // Tear down scope hierarchy
    __Vhier.remove(0, __Vscopep_PixelLogic);
    __Vhier.remove(__Vscopep_PixelLogic, __Vscopep_PixelLogic__PixelCTRL);
    __Vhier.remove(__Vscopep_PixelLogic, __Vscopep_PixelLogic__TotCounter);
    __Vhier.remove(__Vscopep_PixelLogic, __Vscopep_PixelLogic__TotMemory);
    __Vhier.remove(__Vscopep_PixelLogic__PixelCTRL, __Vscopep_PixelLogic__PixelCTRL__CG_tot_rst);
    __Vhier.remove(__Vscopep_PixelLogic__TotCounter, __Vscopep_PixelLogic__TotCounter__ff0);
    __Vhier.remove(__Vscopep_PixelLogic__TotCounter, __Vscopep_PixelLogic__TotCounter__ff1);
    __Vhier.remove(__Vscopep_PixelLogic__TotCounter, __Vscopep_PixelLogic__TotCounter__ff2);
    __Vhier.remove(__Vscopep_PixelLogic__TotCounter, __Vscopep_PixelLogic__TotCounter__ff3);
    __Vhier.remove(__Vscopep_PixelLogic__TotCounter, __Vscopep_PixelLogic__TotCounter__ff4);
    __Vhier.remove(__Vscopep_PixelLogic__TotCounter, __Vscopep_PixelLogic__TotCounter__ff5);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET__);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET__);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET__);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET__);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET__);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET__);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET__);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET__);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch);
    __Vhier.remove(__Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch);
    // Clear keys from hierarchy map after values have been removed
    __Vhier.clear();
    // Tear down scopes
    VL_DO_CLEAR(delete __Vscopep_PixelLogic, __Vscopep_PixelLogic = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__PixelCTRL, __Vscopep_PixelLogic__PixelCTRL = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__PixelCTRL__CG_tot_rst, __Vscopep_PixelLogic__PixelCTRL__CG_tot_rst = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotCounter, __Vscopep_PixelLogic__TotCounter = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotCounter__ff0, __Vscopep_PixelLogic__TotCounter__ff0 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotCounter__ff1, __Vscopep_PixelLogic__TotCounter__ff1 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotCounter__ff2, __Vscopep_PixelLogic__TotCounter__ff2 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotCounter__ff3, __Vscopep_PixelLogic__TotCounter__ff3 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotCounter__ff4, __Vscopep_PixelLogic__TotCounter__ff4 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotCounter__ff5, __Vscopep_PixelLogic__TotCounter__ff5 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory, __Vscopep_PixelLogic__TotMemory = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__0__KET____MultiBitLatch = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__1__KET____MultiBitLatch = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__2__KET____MultiBitLatch = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__3__KET____MultiBitLatch = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__4__KET____MultiBitLatch = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__5__KET____MultiBitLatch = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__6__KET____MultiBitLatch = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET__, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch, __Vscopep_PixelLogic__TotMemory__TotMem__BRA__7__KET____MultiBitLatch = nullptr);
    VL_DO_CLEAR(delete __Vscopep_TOP, __Vscopep_TOP = nullptr);
    // Tear down sub module instances
}
